# -*- coding: utf-8 -*-
r"""hw_03_gradient_boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ry8uFan4cs4PPZAKrUFrgPfcNNzccb8a

# Домашнее задание. Решение задачи регрессии с помощью градиентного бустинга
В этом домашнем задании вы примените алгоритм градиентного бустинга к задаче регрессии. Мы будем решать задачу предсказания популярности трека на музыкальной платформе по различным характеристикам (имя музыканта, продолжительность, а также численные характеристика трека, такие как размер, громкость, лад (минор/мажор), энергичность, акустичность и т.д.

## Почему именно градиентный бустинг?
Обычно градиентный бустинг дает в стандартных задачах машинного обучения на табличных данных умеренный прирост по сравнению со случайным лесом: несколько процентных пунктов целевой метрики. В предлагаемой вам задаче все иначе: градиентный бустинг в библиотеке `CatBoost` здесь дает по сравнению с бейзлайном **четырехкратный** прирост по метрике $R^2$. Помимо самого алгоритма бустинга, это связано со способностью `CatBoost` качественно кодировать категориальные признаки, тогда как стандартные модели машинного обучения в `sklearn` (как и альтернативные реализации градиентного бустинга) по умолчанию этого делать не умеют. При выполнении домашнего задания вам предстоит в этом убедиться.

## Данные и посылка
в этом задании мы будем проверять и оценивать вашу посылку так, как это происходит на конкурсах по машинному обучению (например, на платформе kaggle.com). Для этого мы предварительно разделили данные в задании на две части.

1. data_train.csv. В каждой строчке файла data_train.csv содержатся следующие поля:
* `track_id` --- уникальный ключ, который мы будем использовать в качестве `pd.Index`
* `artist_name` --- имя исполнителя (важный категориальный признак, качественное использование которого кратно повышает качество модели)
* `track_name` --- название трека. Это поле не используется в базовом решении и в авторском решении, но никто не мешает вам попробовать его использовать
* `acousticness` --- числовой признак
* `danceability` --- числовой признак
* `duration_ms` --- числовой признак
* `energy` --- числовой признак
* `instrumentalness` --- числовой признак
* `key` --- категориальный признак
* `liveliness` --- числовой признак
* `loudness` --- числовой признак
* `mode` --- бинарный признак
* `speechiness`	--- числовой признак
* `tempo` --- числовой признак
* `time_signature` --- категориальный признак
* `valence` --- числовой признак
* `popularity` --- целевая переменная, принимающая целое значение от 1 до 100.

На этом наборе данных вам необходимо создать и обучить модель.

2. data_scoring.csv. В каждой строчке файла data_scoring.csv указаны признаки тестовых объектов. Предсказания для этого набора необходимо записать в файл submission.csv и сдать в соответствующий шаг на Stepik. Количество попыток ограничено 100 штук.
Также мы предоставляем файл [sample_submission.csv](https://drive.google.com/file/d/1QlQnKFOej3hg5tNcjx4DRrd6QPNdTl_7/view?usp=share_link). Это образец посылки --- ваш файл submission.csv должен быть оформлен таким же образом. Обратите внимание, что порядок строчек в submission должен быть такой же, как и в data_scoring.csv!

## Целевая метрика
Целевая метрика в этой задаче --- $R^2$. Именно по ней система будет выставлять вам баллы. Минимальное значение $R^2$, за которое ставятся баллы, равно $lb=0.450$. Чтобы набрать полный балл за задание, необходимо набрать $ub=0.475$.
Оценка выставляется по формуле
$$\begin{cases}
0, & score \leqslant lb,\\
10 \cdot \frac{score - lb}{ub - lb}, & lb < score < ub,\\
10, & score \geqslant ub.
\end{cases}$$

## Бейзлайн
В этом ноутбуке приведен бейзлайн на основе случайного леса, который оценивается в 0 баллов на Stepik (дает $R^2=0.15$).

## Ход работы
Для получения необходимого качества предлагаем использовать модель `catboost.CatBoostRegressor`. Эта модель с любыми параметрами скорее всего принесет вам какие-то баллы за задание. При этом максимальный балл принесет модель, у которой подобран оптимальный параметр глубины. Для нахождения этого параметра мы предлагаем использовать кросс-валидацию, встроенную в `catboost`.

Обратите внимание, что кодирование категориальных признаков, принятое по умолчанию в `catboost`, работает лучше, чем выделение числовых признаков с помощью One-hot Encoding. Поэтому вам этот этап обработки данных не понадобится, хотя он и реализован в бейзлайне. Для того, чтобы указать `catboost`, какие данные являются категориальными, необходимо использовать параметр `cat_features` при создании `catboost.Pool`.

Желаем удачи!
"""

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor

# Зависимости: pip install "scikit-learn>=1.2" catboost pandas matplotlib tqdm
# Данные (Google Drive, файлы курса):
#   gdown 1G-dH-66bWsl16RC9n8AX4370I2LRkgzO  -> data_train.csv
#   gdown 1pVrpyO5ZxouaDGYW29L0mWUnognmiZIq  -> data_scoring.csv
# Можно скачать вручную или запустить скрипт с флагом --download (нужен pip install gdown).

GDRIVE_FILES = {
    'data_train.csv': '1G-dH-66bWsl16RC9n8AX4370I2LRkgzO',
    'data_scoring.csv': '1pVrpyO5ZxouaDGYW29L0mWUnognmiZIq',
}

CAT_FEATURES_BASELINE = ['artist_name', 'key', 'time_signature']
CAT_FEATURES_CATBOOST = ['artist_name', 'key', 'time_signature', 'mode']


def download_data(data_dir: Path) -> None:
    """Скачивает CSV с Google Drive через gdown (аналог `!gdown` из ноутбука)."""
    data_dir.mkdir(parents=True, exist_ok=True)
    for name, file_id in GDRIVE_FILES.items():
        target = data_dir / name
        if target.exists():
            continue
        subprocess.run([sys.executable, '-m', 'gdown', file_id, '-O', str(target)], check=True)


def run_baseline(data: pd.DataFrame, data_scoring: pd.DataFrame, out_dir: Path) -> None:
    """Бейзлайн: One-hot Encoding + RandomForestRegressor с перебором max_depth."""
    cat_features = CAT_FEATURES_BASELINE

    X_train, X_test, y_train, y_test = train_test_split(
        data.drop(columns=['popularity']),
        data['popularity'])

    # Кодируем категориальные данные (кроме artist_name) через OneHotEncoder.
    encoder = OneHotEncoder(max_categories=30, sparse_output=False, handle_unknown='ignore')
    train_cat_data = pd.DataFrame(encoder.fit_transform(X_train[cat_features[1:]]),
                                  index=X_train.index,
                                  columns=encoder.get_feature_names_out())
    test_cat_data = pd.DataFrame(encoder.transform(X_test[cat_features[1:]]),
                                 index=X_test.index,
                                 columns=encoder.get_feature_names_out())

    full_train_data = pd.concat([X_train.drop(columns=cat_features + ['track_name']),
                                 train_cat_data],
                                axis='columns')
    full_test_data = pd.concat([X_test.drop(columns=cat_features + ['track_name']),
                                test_cat_data],
                               axis='columns')

    # Перебираем max_depth, считаем R2 на train и test.
    depths = np.arange(8, 17)
    rf_metrics = []
    for depth in tqdm(depths):
        rf_model = RandomForestRegressor(n_estimators=100,
                                         max_depth=depth,
                                         n_jobs=-1).fit(full_train_data, y_train)
        rf_metrics.append({'train': r2_score(y_train, rf_model.predict(full_train_data)),
                           'test': r2_score(y_test, rf_model.predict(full_test_data))})

    plt.figure(figsize=(10, 6))
    plt.plot(depths, [m['test'] for m in rf_metrics], label='Random Forest test R2', color='red')
    plt.scatter(depths, [m['test'] for m in rf_metrics], color='red')
    plt.plot(depths, [m['train'] for m in rf_metrics], label='Random Forest train R2', color='blue')
    plt.scatter(depths, [m['train'] for m in rf_metrics], color='blue')
    plt.xlabel('depth')
    plt.ylabel('R2-score')
    plt.grid()
    plt.legend()
    plt.savefig(out_dir / 'rf_depth_r2.png')
    plt.close()

    # Оптимальная глубина в исходном ноутбуке: max_depth=15.
    # Для scoring используется уже обученный encoder (transform, а не fit_transform),
    # чтобы набор one-hot колонок совпадал с обучающим.
    scoring_cat_data = pd.DataFrame(encoder.transform(data_scoring[cat_features[1:]]),
                                    index=data_scoring.index,
                                    columns=encoder.get_feature_names_out())
    full_scoring_data = pd.concat([data_scoring.drop(columns=cat_features + ['track_name']),
                                   scoring_cat_data],
                                  axis='columns')

    model = RandomForestRegressor(max_depth=15)
    model.fit(full_train_data, y_train)
    y_scoring = np.clip(model.predict(full_scoring_data), 0, 100)

    # Порядок строк в submission должен совпадать с data_scoring.csv.
    submission = pd.Series(y_scoring, index=data_scoring.index, name='popularity')
    submission.to_csv(out_dir / 'baseline_submission.csv')


def run_catboost(data: pd.DataFrame, data_scoring: pd.DataFrame, out_dir: Path) -> None:
    """CatBoostRegressor со встроенным кодированием категорий и подбором depth через CV."""
    from catboost import CatBoostRegressor, Pool, cv

    cat_features = CAT_FEATURES_CATBOOST

    print("Missing values in training data:")
    print(data.isnull().sum())
    print("\nMissing values in scoring data:")
    print(data_scoring.isnull().sum())

    X_train = data.drop(columns=['popularity'])
    y_train = data['popularity']
    X_scoring = data_scoring.copy()

    # track_name не используется (и в scoring есть пропуск), удаляем.
    X_train = X_train.drop(columns=['track_name'])
    X_scoring = X_scoring.drop(columns=['track_name'])

    train_pool = Pool(data=X_train, label=y_train, cat_features=cat_features)
    scoring_pool = Pool(data=X_scoring, cat_features=cat_features)

    best_r2 = -np.inf
    best_depth = None
    for depth in range(4, 11):
        params = {
            'iterations': 100,
            'learning_rate': 0.1,
            'depth': depth,
            'random_seed': 42,
            'loss_function': 'RMSE',
            'eval_metric': 'R2',
            'verbose': 0,
        }
        print(f"Performing CV for depth: {depth}")
        scores = cv(pool=train_pool, params=params, fold_count=5, plot=False)
        mean_r2 = scores['test-R2-mean'].iloc[-1]
        print(f"CV R2 for depth {depth}: {mean_r2}")
        if mean_r2 > best_r2:
            best_r2 = mean_r2
            best_depth = depth

    print(f"\nOptimal depth found: {best_depth} with R2: {best_r2}")

    model = CatBoostRegressor(
        iterations=100,
        learning_rate=0.1,
        depth=best_depth,
        random_seed=42,
        loss_function='RMSE',
        eval_metric='R2',
        verbose=0,
    )
    model.fit(train_pool)

    y_scoring = np.clip(model.predict(scoring_pool), 1, 100)
    submission = pd.Series(y_scoring, index=data_scoring.index, name='popularity')
    submission.to_csv(out_dir / 'submission.csv')


def main() -> None:
    parser = argparse.ArgumentParser(description='Регрессия популярности треков: RandomForest и CatBoost')
    parser.add_argument('--data-dir', type=Path, default=Path('.'),
                        help='каталог с data_train.csv и data_scoring.csv')
    parser.add_argument('--out-dir', type=Path, default=Path('.'),
                        help='куда писать submission и графики')
    parser.add_argument('--download', action='store_true',
                        help='скачать данные через gdown, если их нет в --data-dir')
    parser.add_argument('--skip-baseline', action='store_true',
                        help='не запускать бейзлайн RandomForest')
    args = parser.parse_args()

    if args.download:
        download_data(args.data_dir)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    data = pd.read_csv(args.data_dir / 'data_train.csv', index_col='track_id')
    data_scoring = pd.read_csv(args.data_dir / 'data_scoring.csv', index_col='track_id')

    if not args.skip_baseline:
        run_baseline(data, data_scoring, args.out_dir)
    run_catboost(data, data_scoring, args.out_dir)


if __name__ == '__main__':
    main()


# Итоги исходного ноутбука (Colab):
# * пропусков в train нет, в scoring один пропуск в track_name;
# * категориальные признаки: artist_name, key, time_signature, mode;
# * кросс-валидация выбрала depth=10, CV R2 ~0.4837 (бейзлайн RandomForest по условию задания даёт R2=0.15).
