# -*- coding: utf-8 -*-
"""hw_03_gradient_boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ry8uFan4cs4PPZAKrUFrgPfcNNzccb8a

# Домашнее задание. Решение задачи регрессии с помощью градиентного бустинга
В этом домашнем задании вы примените алгоритм градиентного бустинга к задаче регрессии. Мы будем решать задачу предсказания популярности трека на музыкальной платформе по различным характеристикам (имя музыканта, продолжительность, а также численные характеристика трека, такие как размер, громкость, лад (минор/мажор), энергичность, акустичность и т.д.

## Почему именно градиентный бустинг?
Обычно градиентный бустинг дает в стандартных задачах машинного обучения на табличных данных умеренный прирост по сравнению со случайным лесом: несколько процентных пунктов целевой метрики. В предлагаемой вам задаче все иначе: градиентный бустинг в библиотеке `CatBoost` здесь дает по сравнению с бейзлайном **четырехкратный** прирост по метрике $R^2$. Помимо самого алгоритма бустинга, это связано со способностью `CatBoost` качественно кодировать категориальные признаки, тогда как стандартные модели машинного обучения в `sklearn` (как и альтернативные реализации градиентного бустинга) по умолчанию этого делать не умеют. При выполнении домашнего задания вам предстоит в этом убедиться.

## Данные и посылка
в этом задании мы будем проверять и оценивать вашу посылку так, как это происходит на конкурсах по машинному обучению (например, на платформе kaggle.com). Для этого мы предварительно разделили данные в задании на две части.

1. data_train.csv. В каждой строчке файла data_train.csv содержатся следующие поля:
* `track_id` --- уникальный ключ, который мы будем использовать в качестве `pd.Index`
* `artist_name` --- имя исполнителя (важный категориальный признак, качественное использование которого кратно повышает качество модели)
* `track_name` --- название трека. Это поле не используется в базовом решении и в авторском решении, но никто не мешает вам попробовать его использовать
* `acousticness` --- числовой признак
* `danceability` --- числовой признак
* `duration_ms` --- числовой признак
* `energy` --- числовой признак
* `instrumentalness` --- числовой признак
* `key` --- категориальный признак
* `liveliness` --- числовой признак
* `loudness` --- числовой признак
* `mode` --- бинарный признак
* `speechiness`	--- числовой признак
* `tempo` --- числовой признак
* `time_signature` --- категориальный признак
* `valence` --- числовой признак
* `popularity` --- целевая переменная, принимающая целое значение от 1 до 100.

На этом наборе данных вам необходимо создать и обучить модель.

2. data_scoring.csv. В каждой строчке файла data_scoring.csv указаны признаки тестовых объектов. Предсказания для этого набора необходимо записать в файл submission.csv и сдать в соответствующий шаг на Stepik. Количество попыток ограничено 100 штук.
Также мы предоставляем файл [sample_submission.csv](https://drive.google.com/file/d/1QlQnKFOej3hg5tNcjx4DRrd6QPNdTl_7/view?usp=share_link). Это образец посылки --- ваш файл submission.csv должен быть оформлен таким же образом. Обратите внимание, что порядок строчек в submission должен быть такой же, как и в data_scoring.csv!

## Целевая метрика
Целевая метрика в этой задаче --- $R^2$. Именно по ней система будет выставлять вам баллы. Минимальное значение $R^2$, за которое ставятся баллы, равно $lb=0.450$. Чтобы набрать полный балл за задание, необходимо набрать $ub=0.475$.
Оценка выставляется по формуле
$$\begin{cases}
0, & score \leqslant lb,\\
10 \cdot \frac{score - lb}{ub - lb}, & lb < score < ub,\\
10, & score \geqslant ub.
\end{cases}$$

## Бейзлайн
В этом ноутбуке приведен бейзлайн на основе случайного леса, который оценивается в 0 баллов на Stepik (дает $R^2=0.15$).

## Ход работы
Для получения необходимого качества предлагаем использовать модель `catboost.CatBoostRegressor`. Эта модель с любыми параметрами скорее всего принесет вам какие-то баллы за задание. При этом максимальный балл принесет модель, у которой подобран оптимальный параметр глубины. Для нахождения этого параметра мы предлагаем использовать кросс-валидацию, встроенную в `catboost`.

Обратите внимание, что кодирование категориальных признаков, принятое по умолчанию в `catboost`, работает лучше, чем выделение числовых признаков с помощью One-hot Encoding. Поэтому вам этот этап обработки данных не понадобится, хотя он и реализован в бейзлайне. Для того, чтобы указать `catboost`, какие данные являются категориальными, необходимо использовать параметр `cat_features` при создании `catboost.Pool`.

Желаем удачи!
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

# %matplotlib inline

# !pip install catboost # Не будем использовать в этом ноутбуке
!pip install scikit-learn==1.2 # Новая версия One-hot encoding доступна только в sklearn 1.2

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor

"""Скачиваем данные"""

!gdown 1G-dH-66bWsl16RC9n8AX4370I2LRkgzO  # data_train.csv
!gdown 1pVrpyO5ZxouaDGYW29L0mWUnognmiZIq  # data_scoring.csv

data = pd.read_csv('data_train.csv', index_col='track_id')
data.head()

"""Разбиваем на train и test"""

X_train, X_test, y_train, y_test = train_test_split(
    data.drop(columns=['popularity']),
    data['popularity'])

cat_features = ['artist_name', 'key', 'time_signature']

"""Кодируем категориальные данные с помощью `sklearn.preprocessing.OneHotEncoder`. Формируем полный датасет с помощью `pd.concat`."""

encoder = OneHotEncoder(max_categories=30, sparse=False, handle_unknown='ignore')
train_cat_data = pd.DataFrame(encoder.fit_transform(X_train[cat_features[1:]]),
                              index=X_train.index,
                              columns=encoder.get_feature_names_out())

test_cat_data = pd.DataFrame(encoder.transform(X_test[cat_features[1:]]),
                             index=X_test.index,
                             columns=encoder.get_feature_names_out())

full_train_data = pd.concat([X_train.drop(columns=cat_features + ['track_name']),
                             train_cat_data],
                            axis='columns')
full_test_data = pd.concat([X_test.drop(columns=cat_features + ['track_name']),
                            test_cat_data],
                           axis='columns')

"""Перебираем параметр `max_depth` у модели sklearn.ensemble.RandomForestRegressor. Считаем метрики на train, test."""

rf_metrics = []
for depth in tqdm(range(8, 17)):
    rf_model = RandomForestRegressor(n_estimators=100,
                                     max_depth=depth,
                                     n_jobs=-1).fit(
        full_train_data,
        y_train)
    rf_metrics.append({'train': r2_score(y_train, rf_model.predict(full_train_data)),
                       'test': r2_score(y_test, rf_model.predict(full_test_data))})

plt.figure(figsize=(10,6))
plt.plot(np.arange(8, 17),
         [item['test'] for item in rf_metrics],
         label='Random Forest test R2', color='red')
plt.scatter(np.arange(8, 17),
            [item['test'] for item in rf_metrics],
            color='red')

plt.plot(np.arange(8, 17),
         [item['train'] for item in rf_metrics],
         label='Random Forest train R2', color='blue')
plt.scatter(np.arange(8, 17),
            [item['train'] for item in rf_metrics],
            color='blue')

plt.xlabel('depth')
plt.ylabel('R2-score')
plt.grid()
plt.legend()

plt.figure(figsize=(10,6))
plt.plot(np.arange(8, 17),
         [item['test'] for item in rf_metrics],
         label='Random Forest test R2', color='red')
plt.scatter(np.arange(8, 17),
            [item['test'] for item in rf_metrics],
            color='red')

plt.xlabel('depth')
plt.ylabel('R2-score')
plt.grid()
plt.legend()

"""Оптимальный параметр глубины --- `max_depth=15`. Обучим окончательную модель, предскажем ответы на `data_scoring` и сформируем submission."""

data_scoring = pd.read_csv('data_scoring.csv', index_col='track_id')
data_scoring.head()

scoring_cat_data = pd.DataFrame(encoder.fit_transform(data_scoring[cat_features[1:]]),
                              index=data_scoring.index,
                              columns=encoder.get_feature_names_out())

full_scoring_data = pd.concat([data_scoring.drop(columns=cat_features + ['track_name']),
                             scoring_cat_data],
                            axis='columns')

model = RandomForestRegressor(max_depth=15)
model.fit(full_train_data, y_train)

y_scoring = np.clip(model.predict(full_scoring_data), 0, 100)

submission = pd.Series(y_scoring, index=data_scoring.index, name='popularity')
submission.head()

"""Обратите внимание, что порядок строчек в submission должен быть такой же, как и в data_scoring.csv!"""

submission.to_csv('baseline_submission.csv')

"""# Task
Выполни домашнее задание, используя данные из файлов "train.csv" и "test.csv".

## Data loading

### Subtask:
Load the training and scoring data from the provided CSV files into pandas DataFrames.

**Reasoning**:
Load the training and scoring data from the CSV files into pandas DataFrames with `track_id` as the index.
"""

data = pd.read_csv('data_train.csv', index_col='track_id')
data_scoring = pd.read_csv('data_scoring.csv', index_col='track_id')
display(data.head())
display(data_scoring.head())

"""## Data wrangling

### Subtask:
Prepare the data for the CatBoost model. This includes identifying categorical features and potentially handling missing values. Unlike the baseline, we don't need to explicitly one-hot encode categorical features as CatBoost handles this internally.

**Reasoning**:
Identify categorical features, check for missing values, and separate the target variable.
"""

cat_features = ['artist_name', 'key', 'time_signature', 'mode']

# Check for missing values
print("Missing values in training data:")
print(data.isnull().sum())
print("\nMissing values in scoring data:")
print(data_scoring.isnull().sum())

# Separate target variable
X_train = data.drop(columns=['popularity'])
y_train = data['popularity']

X_scoring = data_scoring.copy()

"""**Reasoning**:
Since there is one missing value in the 'track_name' column of the scoring data, and 'track_name' is not used in the baseline model, we will drop this column from both the training and scoring data.


"""

X_train = X_train.drop(columns=['track_name'])
X_scoring = X_scoring.drop(columns=['track_name'])

print("Remaining columns in X_train:")
print(X_train.columns)
print("\nRemaining columns in X_scoring:")
print(X_scoring.columns)

"""## Catboost pool creation

### Subtask:
Create CatBoost Pool objects for the training and scoring data, specifying the categorical features.

**Reasoning**:
Import the Pool class from catboost and create the CatBoost Pool objects for training and scoring data.

**Reasoning**:
The previous command failed because the `catboost` library is not installed. Install `catboost` using pip.
"""

!pip install catboost

"""**Reasoning**:
Now that catboost is installed, create the CatBoost Pool objects for the training and scoring data.


"""

from catboost import Pool

train_pool = Pool(data=X_train,
                  label=y_train,
                  cat_features=cat_features)

scoring_pool = Pool(data=X_scoring,
                    cat_features=cat_features)

"""## Model training

### Subtask:
Train a CatBoostRegressor model on the training data. We will use cross-validation to find the optimal depth parameter for the model, as suggested in the problem description.

**Reasoning**:
Iterate through the defined depth range and perform cross-validation using CatBoost's cv function to find the optimal depth.
"""

from catboost import CatBoostRegressor, cv

depths = range(4, 11)  # Define a reasonable range of depths to search

cv_results = {}
best_r2 = -np.inf
best_depth = None

for depth in depths:
    params = {
        'iterations': 100,
        'learning_rate': 0.1,
        'depth': depth,
        'random_seed': 42,
        'loss_function': 'RMSE',  # Corrected loss function
        'eval_metric': 'R2',  # Add R2 as an evaluation metric
        'verbose': 0  # Suppress verbose output during CV
    }

    print(f"Performing CV for depth: {depth}")
    # Perform cross-validation
    scores = cv(
        pool=train_pool,
        params=params,
        fold_count=5,  # Using 5 folds for cross-validation
        plot=False # Do not plot during CV
    )

    # Get the R2 score from the last iteration
    # The column name for the evaluation metric will be eval_metric-mean
    mean_r2 = scores['test-R2-mean'].iloc[-1]
    cv_results[depth] = mean_r2
    print(f"CV R2 for depth {depth}: {mean_r2}")

    # Track the best depth based on test R2
    if mean_r2 > best_r2:
        best_r2 = mean_r2
        best_depth = depth

print(f"\nOptimal depth found: {best_depth} with R2: {best_r2}")

# Train the final model with the optimal depth
model = CatBoostRegressor(
    iterations=100,
    learning_rate=0.1,
    depth=best_depth,
    random_seed=42,
    loss_function='RMSE', # Use RMSE for final training
    eval_metric='R2', # Evaluate with R2
    verbose=0 # Suppress verbose output during final training
)

model.fit(train_pool)

"""## Prediction

### Subtask:
Make predictions on the scoring data using the trained CatBoost model.

**Reasoning**:
Predict the popularity scores on the scoring data using the trained CatBoost model and clip the predictions to be between 1 and 100.
"""

y_scoring = model.predict(scoring_pool)
y_scoring = np.clip(y_scoring, 1, 100)

"""## Submission file generation

### Subtask:
Create a submission file in the specified format (`submission.csv`) containing the track IDs and the predicted popularity scores.

**Reasoning**:
Create a pandas Series from the predicted popularity scores and save it to a CSV file.
"""

submission = pd.Series(y_scoring, index=data_scoring.index, name='popularity')
submission.to_csv('submission.csv')

"""## Summary:

### Data Analysis Key Findings

*   The training data contained no missing values, while the scoring data had one missing value in the 'track\_name' column.
*   Categorical features were identified as 'artist\_name', 'key', 'time\_signature', and 'mode'.
*   The 'track\_name' column was removed from both datasets.
*   CatBoost Pool objects were successfully created for training and scoring data, including the identified categorical features.
*   Cross-validation was used to find the optimal `depth` parameter for the CatBoost Regressor model, with the optimal depth determined to be 10 based on maximizing the R2 score. The highest R2 achieved during CV for depth 10 was approximately 0.4837.
*   The final CatBoost Regressor model was trained using the optimal depth of 10.
*   Predictions were made on the scoring data using the trained model, and the predicted popularity scores were clipped to the range of 1 to 100.
*   A submission file named `submission.csv` was successfully generated containing the track IDs from the scoring data and the corresponding predicted popularity scores.

### Insights or Next Steps

*   The R2 score obtained during cross-validation (approx. 0.4837) suggests that the model explains about 48.4% of the variance in the popularity scores. Further feature engineering or exploring other model parameters could potentially improve this score.
*   Investigating the features that contribute most significantly to the model's predictions could provide insights into the drivers of track popularity and inform future modeling efforts.

"""